### PR TITLE
Add headers to requests from HTTP monitor

### PR DESCRIPTION
**Pull request by andronkyr**
This PR adds HTTP headers in the respective monitor. 

The headers are expected to be given in a dictionary format, and a possible use case could be the authorization to an *API* service.

One possible configuration could be:

```
[api-with-authorization]
type=http
url=https://api.example.com
headers={"accept": "application/json", "Access-Key" : "Key"}
tolerance=1
allowed_codes=200
```

### CODE REVIEW

**Comment by jamesoff** [comment]
This looks useful, thanks!

Would you be ok with changing the merge target to the develop branch not master? (I didn't get round to changing the default in GitHub yet.) Looks like the CI failure is just a comment formatting thing so if you can just change that (and point at the develop branch) it should be good to merge.

I'm travelling over the next week or so, so may be slow to get back to this :)

**Comment by andronkyr** [comment]
Hello! Thanks for the fast response. Updated the PR to reflect the proposed changes. Looking forward to hearing from you :)

**Comment by jamesoff** [comment]
Looks good to me, thanks!

**Comment by jamesoff** [comment]
Merged by hand due to conflicts :)

**Comment by andronkyr** [comment]
Thank you ;)

**Pull request merged**
