### PR TITLE
Remove pickle

### PR DESCRIPTION
**Pull request by ProgVal**
Use JSON instead. To support a smooth transition, there is a config variable `allow_pickle` (with a default to `true`) that tells a Listener to allow pickle input from old Loggers.

### CODE REVIEW

**Comment by ProgVal** [comment]
Any idea why the travis build fails with "TypeError: getboolean() got an unexpected keyword argument 'fallback'"?

**Comment by jamesoff** [comment]
The 2.7 build is failing with that but the 3.x builds aren't, so I suspect it's a new-to-3.x parameter.

The 3.x builds are failing because of flake8 errors, though.

Thanks for this; I haven't time to look at it until later in the week due to work commitments I'm afraid, but I'll catch up :)

**Comment by ProgVal** [comment]
> Thanks for this; I haven't time to look at it until later in the week due to work commitments I'm afraid, but I'll catch up :)

Sure, no problem. I have my own branch where I merge all my stuff so I can use it immediately.

> [edit: I'm planning on this being the last 2.x-compatible release, FWIW]

Cool :)

**Comment by ProgVal** [comment]
I'm not sure what happened on this PR, but thanks for merging :)

**Comment by jamesoff** [comment]
Hah, mostly it was fixing up things so tests passed and coverage wasn't too bad :)

Thanks again for this, and for the "no more if" one, will take a look at that soon.

**Pull request merged**
