### PR TITLE
Added NMA (Notify My Android) alerter

### PR DESCRIPTION
**Pull request by hrabbit**
- Implemented a simple class to allow Alerts to be sent via NMA. It requires an APIKey only.
  - Uses type=nma
- Renamed base config file to config.ini to remove confusion over monitor.ini vs monitors.ini
- Included a sample config.ini-dist and monitors.ini-dist for a quick start on new installs.
- Implemented notify flag to monitors in order to disable notifications for any checks within the system without disabling the checks themselves.
  - Monitors
    - notify=False (supports 1/0, true/false, True/False)
- Added group based notifications which allows a separation of alerts between different devices, groups, or people.
  - Any Alerters that the monitors "group" is a member of will be checked and allowed to call the send_alert method. This should allow any normal business logic to take place within the existing system.
   - Monitors (without listing, it defaults to "default")
      - group=foo
   - Alerters (without listing, it defaults to "default")
     - groups=group1,group2,foo

Side note.. I am not a Python developer. I just like what the monitor does.

### CODE REVIEW

**Comment by jamesoff** [comment]
Hi, just wanted to say thanks for this work (although I don't have anything Android to try it out with). I've been away and/or busy with work for the last month or so, so let me know when it's ready for me to look at properly and merge!

**Comment by hrabbit** [comment]
Hi James,

Thanks for the kind words. I've added a heap more changes to this pull request (They should have been separate branches) with some features that I specifically wanted in my instance but figured might be nice for others as well. As mentioned in the pull request (updated 10 minutes ago), I'm not a Python developer so any code I'm committing should probably be vetted by somebody that is slightly more in tune with it. Otherwise, I think I've implemented everything I wanted and am more than willing for you take it all, or in part.

As for NMA, I'm pretty happy with it's ability and am using it every day. If there are bugs in it, I'd be more than willing to correct them moving forward. (The API for it is dead simple).

If you would rather each part in a separate pull, please do let me know and I'll break it back down again for you.

thanks again.

**Comment by jamesoff** [comment]
No, that's cool all together now I know they're not necessarily all part of the NMA bit.

**Comment by jamesoff** [comment]
Sorry, this kind of got left behind! I'm merging into into a fork of master as I want to tweak a few things on it (despite the terrible naming scheme, I'm not ready to change the default config file name) before I merge properly. I'll also merge it into my python3 branch ready for that.

Thanks!

**Pull request merged**
