### PR TITLE
Add Command monitor type

### PR DESCRIPTION
**Pull request by jamesoff**
@tlegras - this look like what you had in mind?

I had to make it split the `command` option by space, as you're supposed to pass the command and it's arguments as a sequence (or use `shell=True` and I'm not going anywhere near that :) )

Otherwise this is your code with a couple of minor tweaks, thanks very much!

### CODE REVIEW

**Comment by tlegras** [comment]
Thanks for the merge :)

I was not aware of using split, I haven't practice Python for some times
:), this seems fine, I will test it with my set up.

BTW, This script is really nice, so easy to use! Thanks for that!

**Comment by tlegras** [comment]
I just switch back to the main version. I saw an issue with MonitorCommand if there are spaces in the command path filename or if complex command are passed with double quotes. example:

command="C:\Program Files (x86)\Putty\plink.exe" -ssh 1.2.3.4 -l john "sudo service food status"

command will be splited because of:
`command = config_options["command"].split(" ")`
like this
['"C:\\Program', 'Files', '(x86)\\Putty\\plink.exe"', '-ssh', '1.2.3.4', '-l', 'john', '"sudo', 'service', 'food', 'status"']

I could fix it removing split and with shell=True

Thierry

**Comment by jamesoff** [comment]
I'm very keen on not using `shell=True` as it's not safe. The correct solution to this is to build the list of arguments separately to the command path/name, and then add the latter to the start of the former.

**Comment by jamesoff** [comment]
@tlegras I've opened a new issue for this problem, please reply there :)

**Pull request merged**
