### PR TITLE
Feature/python3

### PR DESCRIPTION
**Pull request by Cabalist**
Python3 support

### CODE REVIEW

**Comment by azlux** [comment]
Is this pull request will be merge ? Or still in test ?

**Comment by jamesoff** [comment]
To be honest I haven't had a chance to look at it properly recently, and I'm about to be away for two weeks.

Have you tried this branch? Does it work for you? I'll try to find some time to look at it properly once I'm back.

**Comment by shane0** [comment]
network logging doesn't work yet

hmac key needs bytes, still troubleshooting

`Failed to send data: key: expected bytes or bytearray, but got 'str'`

**Comment by jamesoff** [comment]
@Cabalist I merged this in with the other work I had going on (some Python 3 stuff, also subprocess and switching to requests), thanks :)

@shane0 I'm working my way through things trying them out in Python 3, and stuff like that is showing up a lot! Let me know if you get it sorted, else I'll get to it soon (I'm also looking at testing and coverage stuff, figured that would be useful for a big change like this).

**Pull request merged**
